#!/usr/bin/env bash

# Opens a rofi menu with various power options
show_menu() {
    # Menu options
    lock_screen="Lock Screen"
    standby="Suspend"
    reboot="Reboot"
    hibernate="Hibernate"
    shutdown="Shutdown"

    options="$lock_screen\n$standby\n$reboot\n$shutdown"

    # Open rofi menu, read chosen option
    chosen="$(echo -e "$options" | $rofi_command "󰐥")"

    # Match chosen option to command
    case $chosen in
        "" | $divider)
            echo "No option chosen."
            ;;
        $lock_screen)
            light-locker-command --lock
            ;;
        $standby)
            systemctl suspend
            ;;
        $logout)
            loginctl terminate-session $XDG_SESSION_ID
            ;;
        $reboot)
            systemctl reboot
            ;;
        $shutdown)
            systemctl poweroff
            ;;
        *)
            uptime
            ;;
    esac
}


# Rofi command to pipe into, can add any options here
rofi_command="rofi -dmenu -no-fixed-num-lines -i -p"
# rofi_command="rofi -width 30 -dmenu -i -p rofi-power:"

show_menu
