#!/usr/bin/env bash
# Tmux sessionizer adapted from 
# https://github.com/ThePrimeagen/.dotfiles/blob/master/bin/.local/scripts/tmux-sessionizer

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find -L ~/.tms-targets/ -mindepth 2 -maxdepth 2 -type d -printf '%P\n'| fzf)
    if [ ! "$selected" ]; then
        exit 0
    fi
    selected_name=$(basename "$selected" | tr . _)
    selected=$(realpath ~/.tms-targets/$selected)
fi

if [[ -z $selected ]]; then
    exit 0
fi

# ignore errors, we don't care if it already exists
tmux new-session -ds $selected_name -c $selected 2> /dev/null

if [[ -n $TMUX ]]; then
    tmux switch-client -t $selected_name
else
    tmux attach-session -t $selected_name
fi
